# **1. What is the major difference between "`Vector`" and "`Matrix`"?**

Vector is 1D array and Matrix is 2D array.

In [14]:
# **2. How to import `NumPy` library?**

In [15]:
import numpy as np

# **3. Convert the given Python list into NumPy array and check its data type**

In [8]:
import numpy as np
list_1 = [1,2,3,4,5]
numpy_array = np.array(list_1)
display(numpy_array, type(numpy_array))

array([1, 2, 3, 4, 5])

numpy.ndarray

# **4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [10]:
import numpy as np
display(np.arange(6))

array([0, 1, 2, 3, 4, 5])

# **5. Generate an `array of "5" zeros` **

In [16]:
import numpy as np
display(np.zeros(5))

array([0., 0., 0., 0., 0.])

# **6. Generate the following `matrix`.**

In [17]:
import numpy as np
display(np.zeros((3, 4)))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# **7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [18]:
import numpy as np
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [19]:
# **8. Generate an array of "5" tens.**

In [20]:
import numpy as np
print(np.ones(5) * 10)

[10. 10. 10. 10. 10.]


# **9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [21]:
import numpy as np
print(np.arange(52, 100, 2))

[52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


# **10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [22]:
import numpy as np
display(np.linspace(0, 1, 10, retstep=True))

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 np.float64(0.1111111111111111))

# **11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [23]:
vector_array = np.arange(25)
print(vector_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [24]:
matrix_2d = vector_array.reshape(5, 5)
print(matrix_2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# **12. Please generate the following matrix.**

In [25]:
import numpy as np
matrix = np.arange(1, 26).reshape(5, 5) * 0.1
display(matrix)

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

# **13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [26]:
import numpy as np
matrix = np.linspace(0, 24, 25, dtype=int).reshape(5, 5)
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# **14. What is the main difference between `linspace()` and `arange()`?**

arange() is useful when you know the step size you want, while linspace() is useful when you know how many points you need within a given interval.

In [27]:
# **15. How to generate a single random integer number using NumPy built-in function?**

In [28]:
import numpy as np
random_integer = np.random.randint(100)
print(random_integer)

58


# **16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [29]:
import numpy as np
random_matrix = np.random.rand(7, 5)
print(random_matrix)

[[0.09629251 0.40535854 0.90796538 0.8881024  0.84094988]
 [0.60748065 0.39793609 0.54831367 0.71438074 0.64809841]
 [0.63826149 0.96816487 0.93215781 0.55436509 0.33791262]
 [0.56456641 0.64335829 0.89368413 0.01982134 0.7098681 ]
 [0.50855565 0.14451358 0.64434251 0.24079355 0.10637731]
 [0.92557809 0.23830029 0.86972485 0.84043304 0.83460435]
 [0.18829301 0.59074233 0.07095797 0.49030045 0.63074468]]


# **17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [30]:
import numpy as np
identity_matrix = np.identity(5) * 5
print(identity_matrix)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]
